---
- name: create tomcat group
  group:
    name: tomcat
    state: present

- name: create tomcat user 
  user:
    name: tomcat
    group: tomcat
    shell: /bin/false
    home: /opt/tomcat
    
    