---
- name: Give the tomcat group ownership
  file:
    path: /opt/tomcat
    state: directory
    group: tomcat 
    recurse: yes


- name: give the tomcat group read access to the conf directory
  file: 
    path: /opt/tomcat/conf
    state: directory
    mode:  g+r
   
   
   
- name: give the tomcat group execute access to the conf directory
  file: 
    path: /opt/tomcat/conf
    state: directory
    mode:  g+x
    
- name: Make the tomcat user the owner of the webapps
  file:
    path: /opt/tomcat/webapps/
    state: directory
    owner: tomcat
    recurse: yes


- name: Make the tomcat user the owner of the work
  file:
    path: /opt/tomcat/work/
    state: directory
    owner: tomcat
    recurse: yes

- name: Make the tomcat user the owner of the temp
  file:
    path: /opt/tomcat/temp/
    state: directory
    owner: tomcat
    recurse: yes

- name: Make the tomcat user the owner of the logs
  file:
    path: /opt/tomcat/logs/
    state: directory
    owner: tomcat
    recurse: yes
